### ISSUE TITLE
Question about Converting a Variable

### ISSUE THREAD

**Issue by onowahoo** [learn-co-curriculum/reading-ios-nsnumber-v-nsinteger#3]
Is this code correct in the Converting a Variable section?

    NSInteger negSevenInt = -7;
    NSUInteger eightUInt = 8;
    CGFloat piFloat = 3.14159265359;
    BOOL isYesBOOL = YES;
    
    NSNumber *negSeven = @(negSeven);
    NSNumber *eight = @(eight);
    NSNumber *pi = @(pi);
    NSNumber *isYes = @(isYes);
    
    NSLog(@"%@, %@, %@, %@", negSevenNumber, eightNumber, piNumber, isYesNumber);

as opposed to this:

    NSInteger negSevenInt = -7;
    NSUInteger eightUInt = 8;
    CGFloat piFloat = 3.14159265359;
    BOOL isYesBOOL = YES;
    
    NSNumber *negSeven = @(negSevenInt);
    NSNumber *eight = @(eightUInt);
    NSNumber *pi = @(piFloat);
    NSNumber *isYes = @(isYesBOOL);
    
    NSLog(@"%@, %@, %@, %@", negSeven, eight, pi, isYes);

**Comment by markedwardmurray** [comment]
Nice catch!
